name: Deploy to EC2 Production

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout main
              uses: actions/checkout@v3
              with:
                  ref: main
            - name: Build
              run: npm run build

    deploy:
        needs: build
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout main
              uses: actions/checkout@v3
              with:
                  ref: main
            - name: Deploy to EC2
              env:
                  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                  HOST_NAME: ${{ secrets.HOST_NAME }}
                  USER_NAME: ${{ secrets.USER_NAME }}

              run: |
                  echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
                  ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '

                  cd /home/ubuntu/app/csm/ &&
                  git fetch --all &&
                  git pull --all &&
                  git checkout main &&
                  git pull origin main &&
                  sh build.sh &&
                  echo "Deployed to Staging Successfully" &&
                  pm2 restart all
                  '
